export { RECORD_TYPES } from './constants/recordTypes'

export { useCreateFolder } from './hooks/useCreateFolder'
export { useCreateRecord } from './hooks/useCreateRecord'
export { useCreateVault } from './hooks/useCreateVault'
export { useFavicon } from './hooks/useFavicon'
export { useFolders } from './hooks/useFolders'
export { useInvite } from './hooks/useInvite.js'
export { usePair } from './hooks/usePair'
export { useRecordById } from './hooks/useRecordById'
export { useRecordCountsByType } from './hooks/useRecordCountsByType'
export { useRecords } from './hooks/useRecords'
export { useUserData } from './hooks/useUserData'
export { useVault } from './hooks/useVault'
export { useVaults } from './hooks/useVaults'
export { useBlindMirrors } from './hooks/useBlindMirrors'
export { VaultProvider } from './store'

export { closeAllInstances } from './api/closeAllInstances'
export { setPearpassVaultClient, setStoragePath } from './instances'

export { authoriseCurrentProtectedVault } from './api/authoriseCurrentProtectedVault'
export { fetchFavicon } from './api/fetchFavicon'
export { getVaultById } from './api/getVaultById'
export { getCurrentProtectedVaultEncryption } from './api/getCurrentProtectedVaultEncryption'
export { listRecords } from './api/listRecords'
export { vaultGetFile } from './api/getFile.js'
export { getMasterEncryption } from './api/getMasterEncryption.js'
export { getDefaultFavicon } from './api/getDefaultFavicon.js'
